"""empty message

Revision ID: 04650f8be861
Revises: cba03d66bc8e
Create Date: 2020-04-08 12:54:24.825345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04650f8be861'
down_revision = 'cba03d66bc8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('chort', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'chort')
    # ### end Alembic commands ###
