"""empty message

Revision ID: 33cebd625f74
Revises: 29d8c7eea04c
Create Date: 2020-05-10 13:22:20.285678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cebd625f74'
down_revision = '29d8c7eea04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'id_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('id_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
