"""empty message

Revision ID: 40c6b025500d
Revises: e114281f0cf7
Create Date: 2020-05-10 12:49:00.831263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c6b025500d'
down_revision = 'e114281f0cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('chat_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'chat_name')
    # ### end Alembic commands ###
