"""empty message

Revision ID: 799db702a890
Revises: 33cebd625f74
Create Date: 2020-05-10 13:33:53.451648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799db702a890'
down_revision = '33cebd625f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('id_number', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'id_number')
    # ### end Alembic commands ###
