"""empty message

Revision ID: e114281f0cf7
Revises: fe5ca2e3edd4
Create Date: 2020-04-08 14:55:55.543098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e114281f0cf7'
down_revision = 'fe5ca2e3edd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'id_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('id_number', sa.NUMERIC(precision=15, scale=0), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
