"""empty message

Revision ID: fe5ca2e3edd4
Revises: 04650f8be861
Create Date: 2020-04-08 14:37:33.245137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5ca2e3edd4'
down_revision = '04650f8be861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('rocketchat_user', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('recruit', 'chat_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('chat_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('recruit', 'rocketchat_user')
    # ### end Alembic commands ###
