"""empty message

Revision ID: ff7dbb42863e
Revises: 40c6b025500d
Create Date: 2020-05-10 13:04:18.288027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7dbb42863e'
down_revision = '40c6b025500d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'rocketchat_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('rocketchat_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
